import net.proteanit.sql.DbUtils;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sony
 */
public class pay extends javax.swing.JFrame {
      Connection cn = null;
      PreparedStatement ps = null;
      ResultSet res = null;
    /**
     * Creates new form update
     */
    public pay() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        pay_empid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pay_clear = new javax.swing.JButton();
        pay_cancel = new javax.swing.JButton();
        pay_search = new javax.swing.JButton();
        pay_name = new javax.swing.JLabel();
        pay_lastname = new javax.swing.JLabel();
        pay_dept = new javax.swing.JLabel();
        pay_job = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pay_compute = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        summary = new javax.swing.JTable();
        pay_hours = new javax.swing.JLabel();
        pay_salary = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pay_sss = new javax.swing.JLabel();
        pay_phhealth = new javax.swing.JLabel();
        pay_pagibig = new javax.swing.JLabel();
        pay_tax = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pay_totalsalary = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pay_salaryhour = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel10.setText("Employee ID:");

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel11.setText("Name:");

        jLabel17.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel17.setText("Last Name:");

        jLabel23.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel23.setText("Department:");

        jLabel24.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel24.setText("Job/Position:");

        pay_clear.setText("CLEAR");
        pay_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_clearActionPerformed(evt);
            }
        });

        pay_cancel.setText("CANCEL");
        pay_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_cancelActionPerformed(evt);
            }
        });

        pay_search.setText("Search");
        pay_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_searchActionPerformed(evt);
            }
        });

        jLabel21.setText("Total Number of Hours:");

        jLabel22.setText("Salary:");

        jLabel25.setText("LESS");

        jLabel26.setText("SSS  8%");

        jLabel107.setText("PHIL HEALTH  5%");

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel3.setText("Please enter Employee ID:");

        pay_compute.setText("COMPUTE");
        pay_compute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_computeActionPerformed(evt);
            }
        });

        summary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Month", "Day", "Total Hours"
            }
        ));
        jScrollPane2.setViewportView(summary);
        if (summary.getColumnModel().getColumnCount() > 0) {
            summary.getColumnModel().getColumn(0).setResizable(false);
            summary.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setText("PAG IBIG  2%:");

        jLabel4.setText("WITHHOLDING TAX  12%:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("TOTAL SALARY:");

        pay_totalsalary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setText("Salary per Hour:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pay_empid, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pay_search))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel23))
                                        .addComponent(jLabel24)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pay_job)
                                    .addComponent(pay_dept)
                                    .addComponent(pay_salaryhour)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(pay_lastname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pay_name, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(pay_compute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pay_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pay_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel107)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pay_totalsalary)
                    .addComponent(pay_hours)
                    .addComponent(pay_salary)
                    .addComponent(pay_sss)
                    .addComponent(pay_phhealth)
                    .addComponent(pay_pagibig)
                    .addComponent(pay_tax)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(pay_empid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pay_search))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(pay_name))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(pay_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(pay_dept))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(pay_job))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pay_salaryhour))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pay_compute, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pay_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pay_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(pay_hours))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(pay_salary))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(pay_sss))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel107)
                                    .addComponent(pay_phhealth))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(pay_pagibig))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(pay_tax))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(pay_totalsalary))))
                        .addGap(0, 59, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 960, 450));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 68)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMPLOYEE PAYROLL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\pay.png")); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1120, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pay_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_searchActionPerformed
        
        Function f = new Function();
        res = f.find(pay_empid.getText());
        try{
            if(res.next()){
                pay_name.setText(res.getString("name"));
                pay_lastname.setText(res.getString("lastname"));
                pay_dept.setText(res.getString("department"));
                pay_job.setText(res.getString("job"));
                pay_salaryhour.setText(res.getString("perhour"));
            }
            else{
                JOptionPane.showMessageDialog(null, "Employee ID do not exist!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_pay_searchActionPerformed

    private void pay_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_cancelActionPerformed
        dispose();
        main b = new main();
        b.setVisible(true);
    }//GEN-LAST:event_pay_cancelActionPerformed

    private void pay_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_clearActionPerformed
        pay_name.setText("");
        pay_lastname.setText("");
        pay_empid.setText("");
        pay_dept.setText(" ");
        pay_job.setText(" ");
        pay_salaryhour.setText("");
        pay_hours.setText("");
        pay_salary.setText("");
        pay_sss.setText("");
        pay_pagibig.setText("");
        pay_phhealth.setText("");
        pay_tax.setText("");
        pay_totalsalary.setText("");
        DefaultTableModel model = (DefaultTableModel) summary.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_pay_clearActionPerformed


    private void pay_computeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_computeActionPerformed
        fetch();
        pay_hours.setText(Integer.toString(getsum()));
        int p = (getsum());
        Salary s = new Salary();
        res = s.find(pay_empid.getText());
        double sss = 0.08;
        double ph = 0.05;
        double pagibig = 0.02;
        double tax = 0.12;
        try{
            if(res.next()){
               int r =Integer.parseInt(res.getString("perhour"));
            int min = r * p;
            pay_salary.setText(Integer.toString(min));
            double tsss = sss * min;
            sss = Math.round(sss*100.0)/100.0;
            pay_sss.setText(Double.toString(tsss));
            double tph = ph * min; 
            tph = Math.round(tph*100.0)/100.0;
            pay_phhealth.setText(Double.toString(tph));
            double tpgb = pagibig * min; 
            tpgb = Math.round(tpgb*100.0)/100.0;
            pay_pagibig.setText(Double.toString(tpgb));
            double ttax = tax * min;
            ttax = Math.round(ttax*100.0)/100.0;
            pay_tax.setText(Double.toString(ttax));
            double less = ttax + tpgb + tph + tsss;
            double ttsalary = min - less;
            ttsalary = Math.round(ttsalary*100.0)/100.0;
            pay_totalsalary.setText(Double.toString(ttsalary));
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Incorrect Employee ID");
            
        }
          
    }//GEN-LAST:event_pay_computeActionPerformed
    public void fetch(){
        try{
            cn=DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
            String q = "Select month as 'Month', day as 'Day', totalhours as 'Total Hours' from time where employeeid ="+ pay_empid.getText() +" order by day asc";
            
            ps = cn.prepareStatement(q);
            res=ps.executeQuery();
            
            summary.setModel(DbUtils.resultSetToTableModel(res));
        } 
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Incorrect Employee ID");
        }
    }
    public class Function{
      
        public ResultSet find(String s){
            try{
                cn=DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
                ps = cn.prepareStatement("Select * from employee where employeeid = ?");
                ps.setString(1, s);
                res = ps.executeQuery();
                }      
                catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            return res;
        }
    }
     public class Salary{
      
        public ResultSet find(String s){
            try{
                cn=DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
                ps = cn.prepareStatement("Select perhour from employee where employeeid = ?");
                ps.setString(1, s);
                res = ps.executeQuery();
                }      
                catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            return res;
        }
    }
    public int getsum(){
        int rowsCount = summary.getRowCount();
        int sum = 0;
        for(int i = 0; i < rowsCount; i++){
            sum = sum + Integer.parseInt(summary.getValueAt(i, 2).toString());
            
        }
        return sum;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pay_cancel;
    private javax.swing.JButton pay_clear;
    private javax.swing.JButton pay_compute;
    private javax.swing.JLabel pay_dept;
    private javax.swing.JTextField pay_empid;
    private javax.swing.JLabel pay_hours;
    private javax.swing.JLabel pay_job;
    private javax.swing.JLabel pay_lastname;
    private javax.swing.JLabel pay_name;
    private javax.swing.JLabel pay_pagibig;
    private javax.swing.JLabel pay_phhealth;
    private javax.swing.JLabel pay_salary;
    private javax.swing.JLabel pay_salaryhour;
    private javax.swing.JButton pay_search;
    private javax.swing.JLabel pay_sss;
    private javax.swing.JLabel pay_tax;
    private javax.swing.JLabel pay_totalsalary;
    private javax.swing.JTable summary;
    // End of variables declaration//GEN-END:variables

}

